[tool.poetry]
name = "Alma Handle Portfolios"
version = "0.1"
description = "Handle ExLibris Alma Portfolio Records"
authors = ["Christian Erlinger <christian.erlinger@zhluzern.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
requests = "==2.26.0"